# pip.ini: pip configuration for the Python service
# Tells pip to fetch packages from specific package repositories


[global]
# Point to the Nexus group repo 
index-url = http://localhost:8081/repository/pypi-group-public-first/simple/


# Mark localhost as trusted
trusted-host = localhost