name: hello-world-test

# write a basic yml file to observe the relationship between github and the self-hosted github actions runner
# steps: 1. push the workflow yml file  2. make self-hosted runner run in docker container 3. self-hosted runner registered and received the job from github
# 4. self-hosted runner finished job -> details see /infrastructure/runner/runner_log.txt

on:
  push:
    paths:
      - '.github/workflows/hello-world.yml'
  workflow_dispatch:      # allow re-trigger from the actions tab without another push, meaningful for test stage

jobs:
  hello:
    runs-on: self-hosted   # only a self-hosted runner may take this job. so this job will be queued
    steps:
      - name: hello world runner
        run: echo "hello, I am the self-hosted runner"

      - name: Show where thie runner ran
        run: |
          echo "Runner OS : $RUNNER_OS"
          echo "Hostname  : $(hostname)"
          echo "User      : $(whoami)"
          echo "Directory   : $(pwd)"